### ISSUE TITLE
druid 0.11.0 compatibility

### ISSUE THREAD

**Issue by capistrant** [Zenysis/druid-arbitrary-granularity#1]
More of a general question than concrete issue - 

Has there been any testing with the .10 package against .11? Or is there a plan to create a .11 package in the near future?

**Comment by stephenball1** [comment]
Hey @capistrant,

Just pushed out a 0.12.0 compatible extension binary. Sorry for the incredibly late reply to this, I had missed the notification.

Let me know if you're still interested in 0.11.0 compatibility,
Stephen

**Comment by capistrant** [comment]
I appreciate the update, I’ll be sure to give it a try in our .12
deployments!

Definitely still interested in .11 compatibility as we likely won’t be able
to upgrade our production clusters to .12 for the next 6 months or so.

**Comment by stephenball1** [comment]
Just pushed a .11 compatible extension. The changes I made for .12 were the same ones needed for .11, so it was simple to build the lower version.

**Comment by capistrant** [comment]
Never got back to you about this, but I love the extension. Thanks for your work!
